config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'homes#index'
  resources :users
  resources :topics, only: :index
  resources :menus, only: :index
  resources :events, only: :index
  resources :rooms
  resources :skills
  resources :contact_mails, only: [:new, :create]
  get '/contact_mails', to: 'contact_mails#create', as: 'complete_mail'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_mail.rb
class ContactMail < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room
  #ブロードキャスト
 after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2] #複数追加したいとき -> %i[facebook twitter google_oauth2]

  validate :password_complexity

  mount_uploader :image, ImageUploader

  def password_complexity
    unless self.provider == "google_oauth2"
      return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/
      errors.add :password, '：1文字以上の大文字、小文字、記号を使用してください'
    end
  end

  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[8,20]
    end
  end

  has_many :user_skills
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries
  has_many :skills, through: :user_skills
  accepts_nested_attributes_for :user_skills, allow_destroy: true
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  validates :user_id, uniqueness: { scope: :skill_id }
  belongs_to :user
  belongs_to :skill
end

app/controllers/contact_mails_controller.rb
class ContactMailsController < ApplicationController

  def new
    @contact = ContactMail.new
  end

  def create
    @contact = ContactMail.new(contact_params)
    ContactMailer.contact_mail(@contact).deliver
    flash.now[:notice] = "お問い合わせを受け付けました。"
    redirect_to new_contact_mail_path, alert: "入力に不備があります。" unless @contact.save!
  end

    private

  def contact_params
    params.require(:contact_mail).permit(:name, :email, :subject, :message)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.order(created_at: "DESC")
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @topics = Topic.first(6)
    @users = User.first(12)
    @menus = Menu.first(6)
    @events = Event.order(created_at: "DESC").first(6)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @currentEntries = current_user.entries
     myRoomIds = @currentEntries.map { |entry| entry.room.id }
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @direct_messages = @room.direct_messages
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(name: "DM")
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = @roome.entries.create(entry_params)
    redirect_to @room
  end

  def destroy
      room = Room.find(params[:id])
      room.destroy
      redirect_to users_rooms_path
  end

  private

  def entry_params
    params.require(:entry).permit(:user_id, :room_id)
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def create
  end

  private
  def user_params
    params.require(:skill).permit(:skill)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users_skills = @user.skills.map {|skill| skill.name}
    if user_signed_in?
      @currentUserEntry = current_user.entries
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
      unless @isRoom

        @room = Room.new
        @entry = Entry.new
      end
       end
     end
  end

  def new
    @user = User.find(current_user.id)
    @users_skills = @user.skills.map {|skill| skill.name}
  end

  def edit
    @user = User.find(params[:id])
    @skills = Skill.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "更新しました。"
    else
      flash.now[:alert] = "入力に不備があります。"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :image, :nickname, {  skill_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "info"
    end
  end
end

app/views/contact_mails/create.html.erb
<section id="contact_mails">
  <h5>問い合わせが完了しました</h5>
  <br>
  <p>
    お問い合わせありがとうございます。<br>
    問い合わせ内容は管理者宛にメールで通知しました。<br>
  </p>
  <br>
  <br>
  <h5>問い合わせ内容</h5>
  <p>------------------------------------------------</p>
  <br>
  <br>
  【件名】<br>
  <%= @contact.subject %>
  <br>
  <br>
  【お問い合わせ内容】<br>
  <%= @contact.message %>
  <br>
  <br>
  <p>【返信先】</p>
  <br>
  <%= @contact.email %>
  <br>
  <br>
  <p>------------------------------------------------</p>
</section>

app/views/contact_mails/new.html.erb
<section id="contact_mails">
  <h5>お問い合わせフォーム</h5><br><br>

  <%= form_with model: @contact, url: complete_mail_path, html: { method: :get }, local: true do |f| %> 
    <div class="form-group">
      <label>お名前 <span class="label label-danger">必須</span></label>
      <%= f.text_field :name, class: "form-control", placeholder: "(例) ○○ 太朗",  required: true %>
      <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      <div class="help-block with-errors"></div>
    </div>
    <br>
    <div class="form-group">
      <label>返信先メールアドレス <span class="label label-danger">必須</span></label>
      <%= f.text_field :email, class: "form-control", placeholder: "(例) xxxxxx@gmail.com", required: true %>
      <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      <div class="help-block with-errors"></div>
    </div>
    <br>
    <div class="form-group">
      <label>件名 </label>
      <%= f.text_field :subject, class: "form-control", placeholder: "(例) ○○について" %>
      <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      <div class="help-block with-errors"></div>
    </div>
    <br>
    <div class="form-group">
      <label>お問い合わせ内容 <span class="label label-danger">必須</span></label>
      <%= f.text_area :message, class: "form-control", placeholder: "お問い合わせ内容", rows: "7", required: true %>
      <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      <div class="help-block with-errors"></div>
    </div>
    <div class="col text-center">
    <%= f.submit "送信", class: "btn btn-primary btn-lg w-25" %>
    </div>
  <% end %>
</section>

app/views/contact_mails/show.html.erb
<section id="contact_mails">
  <h5>問い合わせ完了画面</h5><br>
  <p>
    お問い合わせありがとうございます。<br>
    問い合わせ内容は管理者宛にメールで通知しました。<br>
  </p>
<br><br>
  <h5>問い合わせ内容</h5>
  <p>
  ------------------------------------------------<br>
  <br>
  【件名】<br>
  <%= @contact.subject %>
<br><br>
  【お問い合わせ内容】<br>
  <%= @contact.message %>
<br><br>
  【返信先】<br>
  <%= @contact.email %><br>
  <br>
  ------------------------------------------------
  </p>

</section>