config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'homes#index'
  resources :users
  resources :topics, only: :index
  resources :menus, only: :index
  resources :events, only: :index
  resources :rooms
  resources :skills
  resources :contact_mails, only: [:new, :create]
  get '/contact_mails', to: 'contact_mails#create', as: 'complete_mail'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_mail.rb
class ContactMail < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room
  #ブロードキャスト
 after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2] #複数追加したいとき -> %i[facebook twitter google_oauth2]

  validate :password_complexity

  mount_uploader :image, ImageUploader

  def password_complexity
    unless self.provider == "google_oauth2"
      return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/
      errors.add :password, '：1文字以上の大文字、小文字、記号を使用してください'
    end
  end

  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[8,20]
    end
  end

  has_many :user_skills
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries
  has_many :skills, through: :user_skills
  accepts_nested_attributes_for :user_skills, allow_destroy: true
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  validates :user_id, uniqueness: { scope: :skill_id }
  belongs_to :user
  belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:show, :update]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :name, :image])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.order(created_at: "DESC")
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @topics = Topic.first(6)
    @users = User.first(12)
    @menus = Menu.first(6)
    @events = Event.order(created_at: "DESC").first(6)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @currentEntries = current_user.entries
     myRoomIds = @currentEntries.map { |entry| entry.room.id }
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @direct_messages = @room.direct_messages
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(name: "DM")
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = @roome.entries.create(entry_params)
    redirect_to @room
  end

  def destroy
      room = Room.find(params[:id])
      room.destroy
      redirect_to users_rooms_path
  end

  private

  def entry_params
    params.require(:entry).permit(:user_id, :room_id)
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def create
  end

  private
  def user_params
    params.require(:skill).permit(:skill)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    auth = request.env["omniauth.auth"]
    @user = User.from_omniauth(auth)
    session[:google_image] = auth.info.image

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  rescue ActiveRecord::RecordInvalid => e
    redirect_to new_user_registration_url, flash: { errors: e.record.errors.full_messages }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users_skills = @user.skills.map {|skill| skill.name}
    if user_signed_in?
      @currentUserEntry = current_user.entries
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
      unless @isRoom

        @room = Room.new
        @entry = Entry.new
      end
       end
     end
  end

  def new
    @user = User.find(current_user.id)
    @users_skills = @user.skills.map {|skill| skill.name}
  end

  def edit
    @user = User.find(params[:id])
    @skills = Skill.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "更新しました。"
    else
      flash.now[:alert] = "入力に不備があります。"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :image, :nickname, {  skill_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "info"
    end
  end
end

app/views/users/_user.html.erb
<div class="users-card col-lg-2 col-md-12">
  <%= link_to user do%>
  <div class="card">
    <%= image_tag "#{user.image}" ,class:"card-img-top" %>
    <div class="card-body">
      <p class="card-text"><%= user.nickname %></p>
      <!-- <p class="btn btn-primary">コンタクト</p> -->
      <div class="form-text d-none" >
        <%= form_with model: user do |f| %>
          <div class="form-group">
            <%= f.text_area :email , class: 'form-control', value:""%>
          </div>
          <div class="form-group">
            <%= f.submit "送信", class: 'btn btn-primary btn-block'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3>ユーザー編集</h3>

<%= form_with model: @user, local: true do |f| %>
  <% if session[:google_image] %>
    <p>画像を変更したい場合はGoogleアカウントにて変更してください</p>
  <% else %>
    <div class="form_group">
      <label>プロフィール画像：</label>
      <%= f.file_field :image %>
    </div>
  <% end %>

  <div class="form_group">
    <label>お名前：</label>
    <%= f.text_field :nickname, :placeholder => "お名前を入力して下さい"%>
  </div>

  <div class="form_group">
    <label>メールアドレス：</label>
    <%= f.text_field :email, :placeholder => "メールアドレスを入力して下さい"%>
  </div>

  <div class="form_group">
    <label>スキル：</label>
    <%= f.collection_check_boxes(:skill_ids, Skill.all, :id, :name) %>
  </div>

  <div class="btn_group">
    <div class="btn_update">
      <%= f.submit "更新", data: { confirm: "更新しますか？"}, class: "btn btn-success"  %>
    </div>

    <div class="btn_cancel">
      <%= link_to 'キャンセル', user_path(current_user), class:"btn　btn-success"  %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<section id="users">
  <h2>フリーランス一覧</h2>
  <div class="user">
    <div class="container">
      <div class="row">
        <%= render @users %>
      </div>
    </div>
  </div>
</section>

app/views/users/my_show.html.erb
<%= stylesheet_link_tag "_users", :media => "all" %>

<div class="mypage">
  <div class="title">
    <h3>マイページ</h3>
  </div>

  <div class="profile">
    <div class="image">
      <% if @user.image? %>
        <%= image_tag @user.image.url %>
      <% else %>
        <img src="<%= session[:google_image] %>">
      <% end %>
    </div>

    <div class="nickname">
      <label>お名前：</label> <%= @user.nickname %>
    </div>
    <div class="email">
      <label>Eメールアドレス：</label> <%= @user.email %>
    </div>

    <div class="skill">
      <label>スキル：</label> 
      <%= @users_skills.join("、") %>
    </div>
  </div>

  <div class="btn_group">
    <%= link_to '編集', edit_user_path(@user), class:"btn"  %>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "_users", :media => "all" %>

<div class="mypage">
  <div class="title">
    <h3>マイページ</h3>
  </div>

  <div class="profile">
    <div class="image">
      <% if @user.image? %>
        <%= image_tag @user.image.url %>
      <% else %>
        <img src="<%= session[:google_image] %>">
      <% end %>
    </div>

    <div class="nickname">
      <label>お名前：</label> <%= @user.nickname %>
    </div>
    <div class="email">
      <label>Eメールアドレス：</label> <%= @user.email %>
    </div>

    <div class="skill">
      <label>スキル：</label>
      <%= @users_skills.join("、") %>
    </div>
  </div>

 <% unless @user.id != current_user.id %>
   <div class="btn_group">
     <%= link_to '編集', edit_user_path(@user), class:"btn"  %>
   </div>
 <% end %>

<br>
<% if user_signed_in? %>
    <% unless @user.id == current_user.id %>
        <% if @isRoom == true %>
            <%= link_to room_path(@roomId) do %>
                <button id="dm_submit" class="btn btn-primary">コンタクトしますか？</button>
            <% end %>
        <% else %>
            <%= form_for @room, url: rooms_path do |f| %>
                <%= fields_for @entry do |e| %>
                   <%= e.hidden_field :user_id, value: @user.id %>
                <% end %>
                <button type="submit" id="dm_submit" class="btn btn-primary">コンタクトしますか？</button>
            <% end %>
        <% end %>
    <% end %>
<% end %>

</div>