config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'homes#index'
  resources :users
  resources :topics, only: :index
  resources :menus, only: :index
  resources :events, only: :index
  resources :rooms
  resources :skills
  resources :contact_mails, only: [:new, :create]
  get '/contact_mails', to: 'contact_mails#create', as: 'complete_mail'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_mail.rb
class ContactMail < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room
  #ブロードキャスト
 after_create_commit { DirectMessageBroadcastJob.perform_later self }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2] #複数追加したいとき -> %i[facebook twitter google_oauth2]

  validate :password_complexity

  mount_uploader :image, ImageUploader

  def password_complexity
    unless self.provider == "google_oauth2"
      return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/
      errors.add :password, '：1文字以上の大文字、小文字、記号を使用してください'
    end
  end

  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[8,20]
    end
  end

  has_many :user_skills
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries
  has_many :skills, through: :user_skills
  accepts_nested_attributes_for :user_skills, allow_destroy: true
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  validates :user_id, uniqueness: { scope: :skill_id }
  belongs_to :user
  belongs_to :skill
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.order(created_at: "DESC")
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @topics = Topic.first(6)
    @users = User.first(12)
    @menus = Menu.first(6)
    @events = Event.order(created_at: "DESC").first(6)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @currentEntries = current_user.entries
     myRoomIds = @currentEntries.map { |entry| entry.room.id }
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @direct_messages = @room.direct_messages
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(name: "DM")
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = @roome.entries.create(entry_params)
    redirect_to @room
  end

  def destroy
      room = Room.find(params[:id])
      room.destroy
      redirect_to users_rooms_path
  end

  private

  def entry_params
    params.require(:entry).permit(:user_id, :room_id)
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def create
  end

  private
  def user_params
    params.require(:skill).permit(:skill)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users_skills = @user.skills.map {|skill| skill.name}
    if user_signed_in?
      @currentUserEntry = current_user.entries
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
      unless @isRoom

        @room = Room.new
        @entry = Entry.new
      end
       end
     end
  end

  def new
    @user = User.find(current_user.id)
    @users_skills = @user.skills.map {|skill| skill.name}
  end

  def edit
    @user = User.find(params[:id])
    @skills = Skill.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "更新しました。"
    else
      flash.now[:alert] = "入力に不備があります。"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :image, :nickname, {  skill_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "info"
    end
  end
end

app/views/direct_messages/_direct_message.html.erb
<hr>
<p class="<%= direct_message.id %>" style= "color: black; margin-top: 0;">
    <%= direct_message.user.nickname %>
</p>
<p class="<%= direct_message.id %>">
    <span class="balloon1-top">
        <h7 class="dm_content"><%= simple_format(h direct_message.content) %></h7><br>
        <h7 style="color: #C0C0C0;"><%= direct_message.created_at.strftime("%Y/%m/%d %H:%M") %></h7>
    </span>
</p><br>

app/views/direct_messages/_direct_messages.html.erb
<p class="<%= direct_message.id %>" style= "color: white; margin-top: 0;">
    <%= direct_message.user.nickname %>
</p>
<p class="<%= direct_message.id %>">
    <span class="balloon1-top">
        <h7 class="dm_content"><%= simple_format(h direct_message.content) %></h7><br>
        <h7 style="color: #C0C0C0;"><%= direct_message.created_at.strftime("%Y/%m/%d %H:%M") %></h7>
    </span>
</p><br>

app/views/homes/index.html.erb
<section id="homes">
  <h2 class="text-center">トピックス</h2>
  <%= render @topics %>
  <div class="text-center">
    <%= link_to "もっとみる", topics_path %>
  </div>

  <h2 class="text-center">イベント</h2>
  <div class="event">
    <div class="container">
      <div class="row">
        <%= render @events %>
      </div>
    </div>
  </div>
  <div class="text-center">
    <%= link_to  "もっとみる", events_path %>
  </div>

  <h2 class="text-center">メニュー</h2>
  <%= render @menus %>
  <div class="text-center">
    <%= link_to  "もっとみる", menus_path %>
  </div>

  <h2 class="text-center">フリーランス</h2>
  <div class="user">
    <div class="container">
      <div class="row">
        <%= render @users %>
      </div>
    </div>
  </div>
  <div class="text-center">
    <%= link_to "もっとみる", users_path %>
  </div>

  <div class="access">
    <h2 class="text-center">アクセス</h2>
    <div class="row">
      <div class="col-md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3567.2145518941097!2d128.00036311501432!3d26.60956877948031!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x34e45731efe628b9%3A0x589e72d37d8c73e0!2sYANBARUSPACE!5e0!3m2!1sja!2sjp!4v1595573156840!5m2!1sja!2sjp" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
      </div>
      <div class="col-md-6 right">
        <h4>住所</h4>
        <p>〒905-1152 <br>沖縄県名護市字伊差川134−2</p>
        <h4>電話番号</h4>
        <p><a href="tel:090-8801-9200">090-8801-9200</a></p>
        <h4>営業時間</h4>
        <p>10:00~17:00</p>
      </div>
    </div>
  </div>
</section>